### ISSUE TITLE
the API Fuzzer is given Error - Missing PyJFuzz module

### ISSUE THREAD

**Issue by workfast108** [dzonerzy/PyJFAPI#1]
Hello Daniele, 
Thank you for your great tool, it looks promising  and amazing, but 
When i try to use your PyJFAPI fuzzing tool , in Kali Linux , and also in Windows 7 , 
![capture12](https://cloud.githubusercontent.com/assets/24754100/22622611/d9af22ce-eaf3-11e6-98a3-cb7af9aff680.PNG)
 am getting the following Error.

root@kali:~/PyJFAPI# python pjfapi.py -h
Traceback (most recent call last):
  File "pjfapi.py", line 34, in <module>
    from pyjfuzz.lib import PJFConfiguration
ImportError: No module named pyjfuzz.lib

I have attached screenshot of the error also.
Kindly let me know if am doing anything wrong.

Warm Regards
Dere Sewa

**Comment by dzonerzy** [comment]
Hello Dere,

Thank you for your interest in my project, for here it looks like you're missing PyJFuzz library.

You can install it via:

> git clone https://github.com/mseclab/PyJFuzz.git

and then

> sudo python setup.py install 

let me know if this works for you :)

Best Regards,
Daniele

**Comment by workfast108** [comment]
Thanks so much, i got it done the same day itself..,after trying to search around git, for your other projects, i realize on opening the setup.py" file that there is another git project link with PyJFAPI, , everything look good now, I will definitely give feedback regarding your project as i will be using it. and if there is  any suggestion that i have to help improve your project.  i will let you know.

Warm Regards
Dere Sewa

**Comment by dzonerzy** [comment]
As always thank you for your support and let me know about any issue or enhancement!
I'm moving to solved :)

Best Regards,
Daniele

**Comment by dzonerzy** [comment]
Solved installing PyJFuzz library
